config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get '/about' => 'pages#about'
  get '/video' => 'pages#video'
  get '/music' => 'pages#music'
  root 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def create
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def about
    end
    
    def video
    end
    
    def music
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="well">
      <%= form_for @contact do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :comment %>
          <%= f.text_area :comment, class: 'form-control' %>
        </div>
        <%= f.submit 'Submit', class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheSecretHandshakes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Amatic+SC:400,700' rel='stylesheet' type='text/css'>
  </head>
    <body class="background-color">
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: 'navbar-brand ' do %>
          <i class="fa fa-hand-scissors-o"></i>
            
              THE SECRET HANDSHAKES
              <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "ABOUT", about_path %></li>
            <li><%= link_to "VIDEOS", video_path %></li>
            <li><%= link_to "MUSIC", music_path %></li>
            <li><%= link_to "CONTACT", new_contact_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
  
    <div class="container background-color"></div>
      <%= yield %>
    </div>
   </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>We're a band dummy</h1>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
    
</head>
<body>
     
        <div class= "jumbotron text-center">
            <div class='container'>
                <div class='name'>
                    <h1>The Secret Handshakes</h1>
                </div>
           </div>
        </div>
</body>
</html>

app/views/pages/music.html.erb
<div class="container">
<h2>Check out our tunes....Or DIE</h2>
</div>
<div class="container">
    <iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/238777037%3Fsecret_token%3Ds-yA2iC&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>
</div>

app/views/pages/video.html.erb
<div class="container">
    <h2>cutty cuts</h2>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/aavmnt_GiXY" frameborder="0" allowfullscreen></iframe>
</div>
    <div class="container">
        <h2>dis biiitch</h2>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/xKObHTRbIFo" frameborder="0" allowfullscreen></iframe>
    </div>